### ISSUE TITLE
Can't use buttons on SpaceNavigator for Notebooks

### ISSUE THREAD

**Issue by dtecta** [Lasse-B/Sx2vJoy#8]
I've configured vJoy for two buttons, and I've configured Sx2vJoy to map the buttons on a SpaceNavigator to vJoy button #1 and #2. All six axes work fine, however the buttons do not respond. I suspected that this may be due to the USB name difference "SpaceNavigator for Notebooks" rather than just "SpaceNavigator". So, I manually modified "config.ini" in the root of the Sx2vJoy and renamed the two instances of "SpaceNavigator" This did not fix the issue. How do I go about mapping the buttons on a SpaceNavigator for Notebooks? Thanks for any hints.

**Comment by Lasse-B** [comment]
Hey,

the buttons not working properly has been fixed in the test branch of Sx2vJoy, as well as a couple more things:
https://github.com/Lasse-B/Sx2vJoy-test

Don't mind that it says "test", it's actually running more stable with less issues. There's really only some cleanup and cosmetic changes left to do, but I figured I'd rather spend the time on the next version.

Give the test branch a try and let me know how it went.

**Comment by dtecta** [comment]
Hi Lasse,

Thanks for the quick response. The test version does not run with my device.  I have a "SpaceNavigator for Notebooks" not a plain "SpaceNavigator". I do not see it listed in the GUI when assigning buttons. I've tried to run the test version using the default config.ini, after assigning the buttons, and after manually replacing "SpaceNavigator" by "SpaceNavigator for Notebooks". In all three cases, it does not run.

Kind regards,

Gino

**Comment by Lasse-B** [comment]
Hello Gino,

please accept my apologies. I thought I got the button IDs for every controller, but as it turns out nobody had a SpaceNavigator for Notebooks yet who was also willing to supply me with these IDs. If you would be willing to get them, I can add button support for your SN for Notebooks as well.

It's quick and easy. Just download the latest version from the test branch (had to update it once more for this test), press Ctrl+Alt+B on the keyboard and follow the instructions on the tooltip in the upper left corner of your (primary) screen.

The process creates Sx2vJoy.log, located in the same directory as Sx2vJoy. Open the file and check its contents. I'm guessing
`50728`
`0`
`1`
but I could be wrong.

Once I know what the button IDs are, I'll be on my way to get full SN for Notebooks support in.

Sincerely yours,
Karl

**Comment by dtecta** [comment]
Hello Lasse,

You guessed right. The log shows

50728
0
1

Thanks for your assistance.

Gino

**Comment by Lasse-B** [comment]
Hello Gino,

I've updated the test branch to add SpaceNavigator for Notebooks support. Please let me know whether or it this works.

Thanks for helping me add one more device.

Regards,
Karl

**Comment by dtecta** [comment]
Hello Karl,

Awesome, I got button response on my SpaceNavigator for Notebooks. Thank you for your support!

Gino
